{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project',{}) %}

package:
  name: {{ project.get('name') }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_rev: {{ GIT_DESCRIBE_TAG }}
  #git_url: https://github.com/maimonlab/siffpy.git

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install ."

requirements:
  build:
    - python
    - pip
    - wheel
    - setuptools>=45
    - setuptools_scm[toml]>=6.2
  host:
    - python
    - numpy
    - pandas
    - scipy
    - h5py
  run:
    - python
    - numpy
    - pandas
    - scipy
    - h5py
    - ruamel.yaml

test:
#   requires:
#     - pytest
  imports:
    - sifftrac
#   # commands:
  #   - pytest

about:
  home: "https://github.com/maimonlab/sifftrac"
  summary : {{ project.get('description') }}
  license: GPL3
  license_file: ../LICENSE.md

extra:
  recipe-maintainers:
    - StephenThornquist
